# *Part 3 (Array Creation Functions)*

In [1]:
import numpy as np

In [9]:
# a)    Part 1
zero_matrix = np.zeros((4, 4))
print("Zero Matrix (4x4):")
print(zero_matrix)

Zero Matrix (4x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# b)
one_matrix = np.ones((3, 2))
print("One Matrix (3x2):")
print(one_matrix)

One Matrix (3x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
# c)
identity_matrix = np.eye(5)
print("Identity Matrix (5x5):")
print(identity_matrix)

Identity Matrix (5x5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
# d)
constant_array = np.full((3, 3), 7)
print("Constant Array (3x3) filled with 7:")
print(constant_array)


Constant Array (3x3) filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [13]:
# e)
random_array = np.random.randint(10, 100, size=(3, 4))
print("Random Integer Array (3x4) between 10 and 99:")
print(random_array)

Random Integer Array (3x4) between 10 and 99:
[[98 99 36 80]
 [74 14 79 36]
 [64 43 91 40]]


In [15]:
# Part 2
arange_array = np.arange(5, 50, 5).reshape(3, 3)
print("Array from 5 to 50 (step 5), reshaped to (3x3):")
print(arange_array)

Array from 5 to 50 (step 5), reshaped to (3x3):
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
