# *Part 4 (Indexing and Slicing)*

In [17]:
import numpy as np

In [18]:
# Given array
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

In [20]:
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [21]:
# 1. Extract the second row
second_row = arr[1]
print("Second Row:")
print(second_row)

Second Row:
[50 60 70 80]


In [22]:
# 2. Extract the first two rows and the second two columns
first_two_rows_second_two_cols = arr[0:2, 2:4]
print("First two rows & second two columns:")
print(first_two_rows_second_two_cols)

First two rows & second two columns:
[[30 40]
 [70 80]]


In [23]:
# 3. Extract the last column using slicing
last_column = arr[:, -1]
print("Last Column:")
print(last_column)

Last Column:
[ 40  80 120]


In [24]:
# 4. Replace the middle row with [1, 2, 3, 4]
arr[1] = [1, 2, 3, 4]
print("Array after replacing middle row:")
print(arr)

Array after replacing middle row:
[[ 10  20  30  40]
 [  1   2   3   4]
 [ 90 100 110 120]]


# *(Vectorization)*

In [ ]:
import numpy as np

In [ ]:
# 1. Create two arrays A and B of 5 random integers each
A = np.random.randint(1, 20, size=5)
B = np.random.randint(1, 20, size=5)

print("Array A:", A)
print("Array B:", B)

Array A: [ 7 12 19 17 16]
Array B: [ 7  6 13 19  7]


In [ ]:
# Element-wise operations
add_result = A + B
sub_result = A - B
mul_result = A * B
div_result = A / B

print("Addition:     ", add_result)
print("Subtraction:  ", sub_result)
print("Multiplication:", mul_result)
print("Division:     ", div_result)

Addition:      [14 18 32 36 23]
Subtraction:   [ 0  6  6 -2  9]
Multiplication: [ 49  72 247 323 112]
Division:      [1.         2.         1.46153846 0.89473684 2.28571429]


In [ ]:
# 2. mathematical functions
arr = np.array([1, 2, 3, 4, 5])

sqrt_arr = np.sqrt(arr)
exp_arr = np.exp(arr)
sin_arr = np.sin(arr)

print("Original Array:", arr)
print("Square Root:", sqrt_arr)
print("Exponential:", exp_arr)
print("Sine:", sin_arr)
print()


Original Array: [1 2 3 4 5]
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]



In [ ]:
# 3. Celsius to Fahrenheit Conversion
celsius = np.array([0, 10, 20, 25, 30, 35, 40, 45, 50, 100])
fahrenheit = (celsius * 9/5) + 32

print("Celsius to Fahrenheit Conversion:")
print("Celsius:", celsius)
print("Fahrenheit:", fahrenheit)

Celsius to Fahrenheit Conversion:
Celsius: [  0  10  20  25  30  35  40  45  50 100]
Fahrenheit: [ 32.  50.  68.  77.  86.  95. 104. 113. 122. 212.]


# *(Broadcasting)*

In [13]:
import numpy as np

In [ ]:
# Create a 3×3 matrix named A
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original Matrix A:")
print(A)

Original Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# ____ Predict Shapes Before Execution _____

# A shape: (3, 3)
# Adding 10 → Scalar Broadcasting → (3, 3)
# Adding [1, 2, 3] → Row Broadcasting → (3, 3)
# Adding [[1], [2], [3]] → Column Broadcasting → (3, 3)

In [ ]:
# 1. Scalar broadcasting (add 10)
result_scalar = A + 10
print("After Adding 10 (Scalar Broadcasting):")
print(result_scalar)
print("Shape:", result_scalar.shape)

After Adding 10 (Scalar Broadcasting):
[[11 12 13]
 [14 15 16]
 [17 18 19]]
Shape: (3, 3)


In [ ]:
# 2. Row broadcasting (add [1, 2, 3])
row_vector = np.array([1, 2, 3])
result_row = A + row_vector
print("After Adding [1, 2, 3] (Row Broadcasting):")
print(result_row)
print("Shape:", result_row.shape)

After Adding [1, 2, 3] (Row Broadcasting):
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
Shape: (3, 3)


In [20]:
# 3. Column broadcasting (add [[1], [2], [3]])
column_vector = np.array([[1], [2], [3]])
result_column = A + column_vector
print("After Adding [[1], [2], [3]] (Column Broadcasting):")
print(result_column)
print("Shape:", result_column.shape)

After Adding [[1], [2], [3]] (Column Broadcasting):
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
Shape: (3, 3)


# *(Reshape, Flatten, Ravel)*

In [2]:
import numpy as np

In [3]:
# 1. Create an array of numbers from 1–12 and reshape
arr = np.arange(1, 13)
print("Original 1D Array:")
print(arr)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
arr_3x4 = arr.reshape(3, 4)
print("Reshaped to (3×4):")
print(arr_3x4)

Reshaped to (3×4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
arr_2x6 = arr.reshape(2, 6)
print("Reshaped again to (2x6):")
print(arr_2x6)

Reshaped again to (2x6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
# 2. Using .flatten() and .ravel()
two_d = np.array([[1, 2, 3],
                  [4, 5, 6]])

flat_array = two_d.flatten()
ravel_array = two_d.ravel()

print("Original 2D Array:")
print(two_d)

Original 2D Array:
[[1 2 3]
 [4 5 6]]


In [7]:
print("Flattened Array:", flat_array)
print("Raveled Array:", ravel_array)

Flattened Array: [1 2 3 4 5 6]
Raveled Array: [1 2 3 4 5 6]


In [8]:
# Modify flattened and raveled arrays
flat_array[0] = 100
ravel_array[1] = 200

print("Flattened Array:", flat_array)
print("Raveled Array:", ravel_array)

Flattened Array: [100   2   3   4   5   6]
Raveled Array: [  1 200   3   4   5   6]


In [11]:
# 3. Given array: arr = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(1, 10).reshape(3, 3)
print("3) Original Array (3x3):")
print(arr2)

3) Original Array (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# Convert into 1D using flatten() and ravel()
flat = arr2.flatten()
rav = arr2.ravel()

print("Flattened:", flat)
print("Raveled:", rav)

Flattened: [1 2 3 4 5 6 7 8 9]
Raveled: [1 2 3 4 5 6 7 8 9]


In [15]:
# Modify both
flat[0] = 111
rav[1] = 888

print("After modification:")
print("Flattened:", flat)
print("Raveled:", rav)

After modification:
Flattened: [111   2   3   4   5   6   7   8   9]
Raveled: [  1 888   3   4   5   6   7   8   9]


In [16]:
print("Original Array after changes:")
print(arr2)

Original Array after changes:
[[  1 888   3]
 [  4   5   6]
 [  7   8   9]]
